/*
 * bots/bots.proto
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: version not set
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.58
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The BotsBot model module.
 * @module model/BotsBot
 * @version version not set
 */
export default class BotsBot {
  /**
   * Constructs a new <code>BotsBot</code>.
   * @alias module:model/BotsBot
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>BotsBot</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/BotsBot} obj Optional instance to populate.
   * @return {module:model/BotsBot} The populated <code>BotsBot</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new BotsBot();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('firstName'))
        obj.firstName = ApiClient.convertToType(data['firstName'], 'String');
      if (data.hasOwnProperty('username'))
        obj.username = ApiClient.convertToType(data['username'], 'String');
      if (data.hasOwnProperty('studioId'))
        obj.studioId = ApiClient.convertToType(data['studioId'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} id
 */
BotsBot.prototype.id = undefined;

/**
 * @member {String} firstName
 */
BotsBot.prototype.firstName = undefined;

/**
 * @member {String} username
 */
BotsBot.prototype.username = undefined;

/**
 * @member {String} studioId
 */
BotsBot.prototype.studioId = undefined;

