/*
 * bots/bots.proto
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: version not set
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.58
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The BotsAddBotRequest model module.
 * @module model/BotsAddBotRequest
 * @version version not set
 */
export default class BotsAddBotRequest {
  /**
   * Constructs a new <code>BotsAddBotRequest</code>.
   * @alias module:model/BotsAddBotRequest
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>BotsAddBotRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/BotsAddBotRequest} obj Optional instance to populate.
   * @return {module:model/BotsAddBotRequest} The populated <code>BotsAddBotRequest</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new BotsAddBotRequest();
      if (data.hasOwnProperty('token'))
        obj.token = ApiClient.convertToType(data['token'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} token
 */
BotsAddBotRequest.prototype.token = undefined;

