/*
 * bots/bots.proto
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: version not set
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.58
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The BotsSetupBotResponse model module.
 * @module model/BotsSetupBotResponse
 * @version version not set
 */
export default class BotsSetupBotResponse {
  /**
   * Constructs a new <code>BotsSetupBotResponse</code>.
   * @alias module:model/BotsSetupBotResponse
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>BotsSetupBotResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/BotsSetupBotResponse} obj Optional instance to populate.
   * @return {module:model/BotsSetupBotResponse} The populated <code>BotsSetupBotResponse</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new BotsSetupBotResponse();
      if (data.hasOwnProperty('url'))
        obj.url = ApiClient.convertToType(data['url'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} url
 */
BotsSetupBotResponse.prototype.url = undefined;

