/*
 * bots/bots.proto
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: version not set
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.58
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The BotsSetupBotRequest model module.
 * @module model/BotsSetupBotRequest
 * @version version not set
 */
export default class BotsSetupBotRequest {
  /**
   * Constructs a new <code>BotsSetupBotRequest</code>.
   * @alias module:model/BotsSetupBotRequest
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>BotsSetupBotRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/BotsSetupBotRequest} obj Optional instance to populate.
   * @return {module:model/BotsSetupBotRequest} The populated <code>BotsSetupBotRequest</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new BotsSetupBotRequest();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} id
 */
BotsSetupBotRequest.prototype.id = undefined;

