/*
 * bots/bots.proto
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: version not set
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.58
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import BotsBot from './BotsBot';

/**
 * The BotsAddBotResponse model module.
 * @module model/BotsAddBotResponse
 * @version version not set
 */
export default class BotsAddBotResponse {
  /**
   * Constructs a new <code>BotsAddBotResponse</code>.
   * @alias module:model/BotsAddBotResponse
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>BotsAddBotResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/BotsAddBotResponse} obj Optional instance to populate.
   * @return {module:model/BotsAddBotResponse} The populated <code>BotsAddBotResponse</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new BotsAddBotResponse();
      if (data.hasOwnProperty('result'))
        obj.result = BotsBot.constructFromObject(data['result']);
    }
    return obj;
  }
}

/**
 * @member {module:model/BotsBot} result
 */
BotsAddBotResponse.prototype.result = undefined;

