/*
 * bots/bots.proto
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: version not set
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.58
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The CompaniesReserveFromBotRequest model module.
 * @module model/CompaniesReserveFromBotRequest
 * @version version not set
 */
export default class CompaniesReserveFromBotRequest {
  /**
   * Constructs a new <code>CompaniesReserveFromBotRequest</code>.
   * @alias module:model/CompaniesReserveFromBotRequest
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>CompaniesReserveFromBotRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CompaniesReserveFromBotRequest} obj Optional instance to populate.
   * @return {module:model/CompaniesReserveFromBotRequest} The populated <code>CompaniesReserveFromBotRequest</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new CompaniesReserveFromBotRequest();
      if (data.hasOwnProperty('botId'))
        obj.botId = ApiClient.convertToType(data['botId'], 'String');
      if (data.hasOwnProperty('datetime'))
        obj.datetime = ApiClient.convertToType(data['datetime'], 'Date');
    }
    return obj;
  }
}

/**
 * @member {String} botId
 */
CompaniesReserveFromBotRequest.prototype.botId = undefined;

/**
 * @member {Date} datetime
 */
CompaniesReserveFromBotRequest.prototype.datetime = undefined;

