/*
 * bots/bots.proto
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: version not set
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.58
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The CompaniesReserveRequest model module.
 * @module model/CompaniesReserveRequest
 * @version version not set
 */
export default class CompaniesReserveRequest {
  /**
   * Constructs a new <code>CompaniesReserveRequest</code>.
   * @alias module:model/CompaniesReserveRequest
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>CompaniesReserveRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CompaniesReserveRequest} obj Optional instance to populate.
   * @return {module:model/CompaniesReserveRequest} The populated <code>CompaniesReserveRequest</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new CompaniesReserveRequest();
      if (data.hasOwnProperty('studioId'))
        obj.studioId = ApiClient.convertToType(data['studioId'], 'String');
      if (data.hasOwnProperty('userId'))
        obj.userId = ApiClient.convertToType(data['userId'], 'String');
      if (data.hasOwnProperty('serviceId'))
        obj.serviceId = ApiClient.convertToType(data['serviceId'], 'String');
      if (data.hasOwnProperty('datetime'))
        obj.datetime = ApiClient.convertToType(data['datetime'], 'Date');
    }
    return obj;
  }
}

/**
 * @member {String} studioId
 */
CompaniesReserveRequest.prototype.studioId = undefined;

/**
 * @member {String} userId
 */
CompaniesReserveRequest.prototype.userId = undefined;

/**
 * @member {String} serviceId
 */
CompaniesReserveRequest.prototype.serviceId = undefined;

/**
 * @member {Date} datetime
 */
CompaniesReserveRequest.prototype.datetime = undefined;

