/*
 * bots/bots.proto
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: version not set
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.58
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The CompaniesReserveFromBotResponse model module.
 * @module model/CompaniesReserveFromBotResponse
 * @version version not set
 */
export default class CompaniesReserveFromBotResponse {
  /**
   * Constructs a new <code>CompaniesReserveFromBotResponse</code>.
   * @alias module:model/CompaniesReserveFromBotResponse
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>CompaniesReserveFromBotResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CompaniesReserveFromBotResponse} obj Optional instance to populate.
   * @return {module:model/CompaniesReserveFromBotResponse} The populated <code>CompaniesReserveFromBotResponse</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new CompaniesReserveFromBotResponse();
    }
    return obj;
  }
}
