/*
 * bots/bots.proto
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: version not set
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.58
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import UsersUser from './UsersUser';

/**
 * The UsersGetByTelegramIDResponse model module.
 * @module model/UsersGetByTelegramIDResponse
 * @version version not set
 */
export default class UsersGetByTelegramIDResponse {
  /**
   * Constructs a new <code>UsersGetByTelegramIDResponse</code>.
   * @alias module:model/UsersGetByTelegramIDResponse
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>UsersGetByTelegramIDResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/UsersGetByTelegramIDResponse} obj Optional instance to populate.
   * @return {module:model/UsersGetByTelegramIDResponse} The populated <code>UsersGetByTelegramIDResponse</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new UsersGetByTelegramIDResponse();
      if (data.hasOwnProperty('result'))
        obj.result = UsersUser.constructFromObject(data['result']);
    }
    return obj;
  }
}

/**
 * @member {module:model/UsersUser} result
 */
UsersGetByTelegramIDResponse.prototype.result = undefined;

