/*
 * bots/bots.proto
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: version not set
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.58
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The UsersUser model module.
 * @module model/UsersUser
 * @version version not set
 */
export default class UsersUser {
  /**
   * Constructs a new <code>UsersUser</code>.
   * @alias module:model/UsersUser
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>UsersUser</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/UsersUser} obj Optional instance to populate.
   * @return {module:model/UsersUser} The populated <code>UsersUser</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new UsersUser();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('telegramId'))
        obj.telegramId = ApiClient.convertToType(data['telegramId'], 'String');
      if (data.hasOwnProperty('firstName'))
        obj.firstName = ApiClient.convertToType(data['firstName'], 'String');
      if (data.hasOwnProperty('lastName'))
        obj.lastName = ApiClient.convertToType(data['lastName'], 'String');
      if (data.hasOwnProperty('username'))
        obj.username = ApiClient.convertToType(data['username'], 'String');
      if (data.hasOwnProperty('createdAt'))
        obj.createdAt = ApiClient.convertToType(data['createdAt'], 'Date');
    }
    return obj;
  }
}

/**
 * @member {String} id
 */
UsersUser.prototype.id = undefined;

/**
 * @member {String} telegramId
 */
UsersUser.prototype.telegramId = undefined;

/**
 * @member {String} firstName
 */
UsersUser.prototype.firstName = undefined;

/**
 * @member {String} lastName
 */
UsersUser.prototype.lastName = undefined;

/**
 * @member {String} username
 */
UsersUser.prototype.username = undefined;

/**
 * @member {Date} createdAt
 */
UsersUser.prototype.createdAt = undefined;

