/*
 * bots/bots.proto
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: version not set
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.58
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The UsersGetByTelegramIDRequest model module.
 * @module model/UsersGetByTelegramIDRequest
 * @version version not set
 */
export default class UsersGetByTelegramIDRequest {
  /**
   * Constructs a new <code>UsersGetByTelegramIDRequest</code>.
   * @alias module:model/UsersGetByTelegramIDRequest
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>UsersGetByTelegramIDRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/UsersGetByTelegramIDRequest} obj Optional instance to populate.
   * @return {module:model/UsersGetByTelegramIDRequest} The populated <code>UsersGetByTelegramIDRequest</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new UsersGetByTelegramIDRequest();
      if (data.hasOwnProperty('telegramId'))
        obj.telegramId = ApiClient.convertToType(data['telegramId'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} telegramId
 */
UsersGetByTelegramIDRequest.prototype.telegramId = undefined;

