/*
 * bots/bots.proto
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: version not set
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.58
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from "../ApiClient";
import CompaniesReserveRequest from '../model/CompaniesReserveRequest';
import CompaniesReserveResponse from '../model/CompaniesReserveResponse';
import RpcStatus from '../model/RpcStatus';

/**
* CompaniesService service.
* @module api/CompaniesServiceApi
* @version version not set
*/
export default class CompaniesServiceApi {

    /**
    * Constructs a new CompaniesServiceApi. 
    * @alias module:api/CompaniesServiceApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instanc
    e} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }

    /**
     * Callback function to receive the result of the companiesServiceReserve operation.
     * @callback moduleapi/CompaniesServiceApi~companiesServiceReserveCallback
     * @param {String} error Error message, if any.
     * @param {module:model/CompaniesReserveResponse{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {module:model/CompaniesReserveRequest} body 
     * @param {module:api/CompaniesServiceApi~companiesServiceReserveCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    companiesServiceReserve(body, callback) {
      
      let postBody = body;
      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling companiesServiceReserve");
      }

      let pathParams = {
        
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = CompaniesReserveResponse;

      return this.apiClient.callApi(
        '/companies.CompaniesService/Reserve', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

}