/*
 * bots/bots.proto
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: version not set
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.58
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from "../ApiClient";
import BotsAddBotRequest from '../model/BotsAddBotRequest';
import BotsAddBotResponse from '../model/BotsAddBotResponse';
import BotsSetupBotRequest from '../model/BotsSetupBotRequest';
import BotsSetupBotResponse from '../model/BotsSetupBotResponse';
import RpcStatus from '../model/RpcStatus';

/**
* TelegramBotsService service.
* @module api/TelegramBotsServiceApi
* @version version not set
*/
export default class TelegramBotsServiceApi {

    /**
    * Constructs a new TelegramBotsServiceApi. 
    * @alias module:api/TelegramBotsServiceApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instanc
    e} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }

    /**
     * Callback function to receive the result of the telegramBotsServiceAddBot operation.
     * @callback moduleapi/TelegramBotsServiceApi~telegramBotsServiceAddBotCallback
     * @param {String} error Error message, if any.
     * @param {module:model/BotsAddBotResponse{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {module:model/BotsAddBotRequest} body 
     * @param {module:api/TelegramBotsServiceApi~telegramBotsServiceAddBotCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    telegramBotsServiceAddBot(body, callback) {
      
      let postBody = body;
      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling telegramBotsServiceAddBot");
      }

      let pathParams = {
        
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = BotsAddBotResponse;

      return this.apiClient.callApi(
        '/bots.TelegramBotsService/AddBot', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the telegramBotsServiceSetupBot operation.
     * @callback moduleapi/TelegramBotsServiceApi~telegramBotsServiceSetupBotCallback
     * @param {String} error Error message, if any.
     * @param {module:model/BotsSetupBotResponse{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {module:model/BotsSetupBotRequest} body 
     * @param {module:api/TelegramBotsServiceApi~telegramBotsServiceSetupBotCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    telegramBotsServiceSetupBot(body, callback) {
      
      let postBody = body;
      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling telegramBotsServiceSetupBot");
      }

      let pathParams = {
        
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = BotsSetupBotResponse;

      return this.apiClient.callApi(
        '/bots.TelegramBotsService/SetupBot', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

}