/*
 * bots/bots.proto
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: version not set
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.58
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from "../ApiClient";
import RpcStatus from '../model/RpcStatus';
import UsersGetByTelegramIDRequest from '../model/UsersGetByTelegramIDRequest';
import UsersGetByTelegramIDResponse from '../model/UsersGetByTelegramIDResponse';

/**
* UsersService service.
* @module api/UsersServiceApi
* @version version not set
*/
export default class UsersServiceApi {

    /**
    * Constructs a new UsersServiceApi. 
    * @alias module:api/UsersServiceApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instanc
    e} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }

    /**
     * Callback function to receive the result of the usersServiceGetByTelegramID operation.
     * @callback moduleapi/UsersServiceApi~usersServiceGetByTelegramIDCallback
     * @param {String} error Error message, if any.
     * @param {module:model/UsersGetByTelegramIDResponse{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {module:model/UsersGetByTelegramIDRequest} body 
     * @param {module:api/UsersServiceApi~usersServiceGetByTelegramIDCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    usersServiceGetByTelegramID(body, callback) {
      
      let postBody = body;
      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling usersServiceGetByTelegramID");
      }

      let pathParams = {
        
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = UsersGetByTelegramIDResponse;

      return this.apiClient.callApi(
        '/users.UsersService/GetByTelegramID', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

}