name: Generate
env:
  GO_VERSION: '1.23'
on:
  push:

permissions:
  contents: write

jobs:
  buf:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: bufbuild/buf-action@v1
      with:
        setup_only: true

    - name: Generate code
      run: buf generate

    - name: Check for changes
      id: check-changes
      run: |
        if [ -n "$(git status --porcelain)" ]; then
          echo "HAS_CHANGED=true" >> "$GITHUB_OUTPUT"
        else
          echo "No changes to commit" >> $GITHUB_STEP_SUMMARY
        fi

    - name: Push sqlc generated code
      if: steps.check-changes.outputs.HAS_CHANGED == 'true'
      run: |
        git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Update generated go code"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
        
          NEW_COMMIT_HASH=$(git rev-parse HEAD)
          echo "Pushed changes: [$NEW_COMMIT_HASH](https://github.com/${{ github.repository }}/commit/$NEW_COMMIT_HASH)"  >> $GITHUB_STEP_SUMMARY