name: Generate

on:
  push:

permissions:
  contents: write

jobs:
  buf:
    env:
      GO_VERSION: '1.23'
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: bufbuild/buf-action@v1
      with:
        setup_only: true

    - name: Cache Go modules
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Install Protoc Gen Go
      run: go install google.golang.org/protobuf/cmd/protoc-gen-go@latest

    - name: Install Protoc Gen Go GRPC
      run: go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest

    - name: Install Protoc Gen Go GRPC Gateway
      run: go install github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-grpc-gateway@latest

    - name: Add Go bin to PATH
      run: echo "${HOME}/go/bin" >> $GITHUB_PATH

    - name: Generate code
      run: buf generate

    - name: Check for changes
      id: check-changes
      run: |
        if [ -n "$(git status --porcelain)" ]; then
          echo "HAS_CHANGED=true" >> "$GITHUB_OUTPUT"
        else
          echo "No changes to commit" >> $GITHUB_STEP_SUMMARY
        fi

    - name: Push generated code
      if: steps.check-changes.outputs.HAS_CHANGED == 'true'
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add .
        git commit -m "Update generated code"
        git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git

        NEW_COMMIT_HASH=$(git rev-parse HEAD)
        echo "Pushed changes: [$NEW_COMMIT_HASH](https://github.com/${{ github.repository }}/commit/$NEW_COMMIT_HASH)"  >> $GITHUB_STEP_SUMMARY


    - name: Upload swagger file to artifact
      uses: actions/upload-artifact@v4
      with:
        name: swagger.json
        path: ./swagger/apidocs.swagger.json

  js-client:
    runs-on: ubuntu-latest

    needs: buf

    steps:
      - name: Download Swagger File Artifact
        uses: actions/download-artifact@v4
        with:
          name: swagger.json
        continue-on-error: true

      - name: Check if Artifact exists
        run: |
          if [ ! -f swagger.json ]; then
            echo "swagger.json not found, skipping code generation."
            exit 0
          fi

      - name: Install swagger-codegen
        run: |
          wget https://repo1.maven.org/maven2/io/swagger/swagger-codegen-cli/2.4.21/swagger-codegen-cli-2.4.21.jar -O swagger-codegen-cli.jar
          alias swagger-codegen="java -jar swagger-codegen-cli.jar"

      - name: Run Swagger Codegen
        run: |
          swagger-codegen generate \
          -i swagger_file.yaml \
          -l js \
          -o ./client/

      - name: List generated files
        run: ls -R ./client/