/*
 * bots/bots.proto
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: version not set
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.58
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Botsbotsproto);
  }
}(this, function(expect, Botsbotsproto) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Botsbotsproto.TelegramBotsServiceApi();
  });

  describe('(package)', function() {
    describe('TelegramBotsServiceApi', function() {
      describe('telegramBotsServiceAddBot', function() {
        it('should call telegramBotsServiceAddBot successfully', function(done) {
          // TODO: uncomment, update parameter values for telegramBotsServiceAddBot call and complete the assertions
          /*

          instance.telegramBotsServiceAddBot(body, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(Botsbotsproto.BotsAddBotResponse);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('telegramBotsServiceSetupBot', function() {
        it('should call telegramBotsServiceSetupBot successfully', function(done) {
          // TODO: uncomment, update parameter values for telegramBotsServiceSetupBot call and complete the assertions
          /*

          instance.telegramBotsServiceSetupBot(body, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(Botsbotsproto.BotsSetupBotResponse);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
